# Generated by Django 3.2.3 on 2021-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='workouts',
            field=models.ManyToManyField(to='main_app.Workout'),
        ),
    ]
