# Generated by Django 3.2.3 on 2021-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_profile_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sets',
        ),
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='entry',
            name='set1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='set2',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='set3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='set4',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='set5',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
