# Generated by Django 3.2.3 on 2021-06-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_exercise_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.CharField(default='https://www.atehno.md/theme/images/no_image.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(default='https://lh3.googleusercontent.com/proxy/6X3eRz-kEjYAZqTAJ1Ae_kywd-NSXFYJ8DfCzgbHU1v_t6lnBrZmISVCb5f3lcboXPQgYRCclrH1Zqr_qXAMHPMU-ghr2jBm8WS80adIvovHl19DdhozFYVsw60HSw', max_length=1000),
        ),
    ]
